version: '3'

services:
  storage-service-ui:
    build: ./
    volumes:
      - ./dist:/usr/share/nginx/html
      - ../src:/storage-service-ui/src
    ports:
      - 80:80
      - 443:443
    restart: always
