version: '3'

services:
  storage-service-ui:
    build: ./
    volumes:
      - ../src:/storage-service-ui/src
    expose:
      - 80
    restart: always
    networks:
      - storage-service-network


networks:
  default:

  storage-service-network:
    external: true